const CONFIG={API_URL:'',REFRESH_MS:20000};
const START=new Date('2026-08-31T09:00:00+02:00'),END=new Date('2026-08-31T11:00:00+02:00');
const PLACES=[
[1,'Village d’Auteuil','patrimoine','🏘️','Le cœur historique et commerçant d’Auteuil.','Photographiez toute l’équipe devant un détail typique du village.'],[2,'Ressourcerie d’Apprentis d’Auteuil','insolite','♻️','Un lieu solidaire dédié au réemploi.','Trouvez un objet insolite visible depuis l’extérieur.'],[3,'Piscine d’Auteuil','sport','🏊','Une piscine discrète aux portes du bois.','Photo d’équipe devant l’entrée.'],[4,'Lacs et cascade du Bois de Boulogne','nature','🌊','Une parenthèse verte et dépaysante.','Cadrez l’eau et toute l’équipe.'],[5,'Stade Roland-Garros','sport','🎾','Le temple parisien de la terre battue.','Mimez un échange de tennis.'],[6,'Parc des Princes','sport','⚽','L’un des stades les plus célèbres de France.','Formez un ballon humain.'],[7,'Stade Jean-Bouin','sport','🏉','Une architecture sportive contemporaine.','Photo devant la façade ondulée.'],[8,'Statue de Jean de La Fontaine','patrimoine','🦊','Le fabuliste veille sur le jardin du Ranelagh.','Reproduisez la pose d’un personnage de la statue.'],[9,'Franprix','pratique','🛒','Un repère utile pour la vie quotidienne.','Photo rapide devant l’enseigne.'],[10,'Pharmacie Lafayette','pratique','💊','Un service essentiel à repérer dans le quartier.','Photo devant la croix verte.'],[11,'Maison de Balzac','culture','📚','La seule demeure parisienne encore conservée de Balzac.','Photographiez un détail de la façade.'],[12,'Rue Mallet-Stevens','insolite','🏛️','Une rue manifeste de l’architecture moderne.','Créez une composition géométrique.'],[13,'Hippodrome d’Auteuil','sport','🏇','Le grand rendez-vous parisien des courses d’obstacles.','Mimez une arrivée de course.'],[14,'Métro Ranelagh','pratique','Ⓜ️','Une station utile pour vos futurs déplacements.','Photo sous le panneau de station.'],[15,'Musée Marmottan Monet','culture','🎨','Une remarquable collection consacrée à Monet.','Prenez une photo inspirée d’un tableau impressionniste.'],[16,'Jardin des Serres d’Auteuil','nature','🌿','Serres historiques, plantes rares et jardins paisibles.','Trouvez la plante la plus étonnante.'],[17,'Cross-training — Square Tolstoï','sport','🏋️','Un espace gratuit pour bouger en plein air.','Toute l’équipe prend une pose sportive.'],[18,'Hôtel et piscine Molitor','insolite','🏊‍♀️','Une icône Art déco devenue lieu contemporain.','Photo d’équipe devant l’entrée Art déco.']
].map(x=>({id:x[0],name:x[1],cat:x[2],emoji:x[3],desc:x[4],challenge:x[5]}));
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],load=(k,d)=>{try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}},save=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
let team=load('jze2_team',null),subs=load('jze2_subs',[]),distanceM=load('jze2_distance',0),returned=load('jze2_returned',false),selected=null,mode='touriste',filter='tous',watchId=null,lastPos=null,deferredPrompt=null;
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2300)}
function tick(){const n=new Date();let d,l;if(n<START){d=START-n;l='Temps avant le rendez-vous'}else if(n<END){d=END-n;l='Temps restant avant le retour'}else{d=0;l='Mission terminée — retour au Grand Salon'}$('#timerLabel').textContent=l;$('#timer').textContent=[Math.floor(d/36e5),Math.floor(d%36e5/6e4),Math.floor(d%6e4/1e3)].map(v=>String(v).padStart(2,'0')).join(':')}
function go(id){$$('.page').forEach(p=>p.classList.toggle('active',p.id===id));$$('nav button').forEach(b=>b.classList.toggle('active',b.dataset.go===id));if(id==='ranking')refreshRanking();scrollTo({top:$('.hero').offsetHeight-10,behavior:'smooth'})}
function render(){const done=new Set(subs.map(s=>s.placeId)),valid=new Set(subs.filter(s=>s.status==='valid').map(s=>s.placeId));$('#teamEmpty').classList.toggle('hidden',!!team);$('#teamDashboard').classList.toggle('hidden',!team);if(team){$('#teamName').textContent=team.name;$('#teamCode').textContent='Code : '+team.code;$('#modePill').textContent=team.mode==='sportif'?'🏃 Mode sportif':'🚶 Mode touriste'}
$('#placeCount').textContent=done.size;$('#pendingCount').textContent=subs.filter(s=>s.status==='pending').length;$('#distance').textContent=(distanceM/1000).toLocaleString('fr-FR',{minimumFractionDigits:2,maximumFractionDigits:2});$('#teamDistance').textContent=(distanceM/1000).toLocaleString('fr-FR',{minimumFractionDigits:2,maximumFractionDigits:2});$('#teamValid').textContent=valid.size;$('#teamPending').textContent=subs.filter(s=>s.status==='pending').length;$('#progressText').textContent=`${done.size} / ${PLACES.length}`;$('#progressFill').style.width=(done.size/PLACES.length*100)+'%';$('#trackBtn').textContent=watchId?'⏸ Arrêter':'▶ Distance';$('#returnBtn').textContent=returned?'✅ Retour signalé':'🏁 Signaler notre retour au Grand Salon';renderPlaces();renderSubs()}
function renderFilters(){const fs=['tous','sport','culture','nature','insolite','patrimoine','pratique'];$('#filters').innerHTML=fs.map(f=>`<button class="${f===filter?'active':''}" data-filter="${f}">${f[0].toUpperCase()+f.slice(1)}</button>`).join('');$$('[data-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;renderFilters();renderPlaces()})}
function renderPlaces(){const done=new Set(subs.map(s=>s.placeId)),arr=PLACES.filter(p=>filter==='tous'||p.cat===filter);$('#visibleCount').textContent=`${arr.length} lieux`;$('#places').innerHTML=arr.map(p=>`<article class="place ${done.has(p.id)?'done':''}"><div class="emoji">${p.emoji}</div><div><h3>${p.name}</h3><p>${p.desc}</p>${done.has(p.id)?'<span class="status">✓ Preuve enregistrée</span>':''}</div><button data-photo="${p.id}">${done.has(p.id)?'Revoir':'Photo'}</button></article>`).join('');$$('[data-photo]').forEach(b=>b.onclick=()=>openPhoto(+b.dataset.photo))}
function renderSubs(){if(!subs.length){$('#submissions').innerHTML='<p>Aucune preuve enregistrée.</p>';return}$('#submissions').innerHTML=subs.slice().reverse().map(s=>`<div class="submission"><div><b>${s.place}</b><small>${new Date(s.time).toLocaleTimeString('fr-FR',{hour:'2-digit',minute:'2-digit'})} · ${s.status==='valid'?'Validée':'En attente'}</small></div><span>${s.status==='valid'?'✅':'🟠'}</span></div>`).join('')}
function openPhoto(id){if(!team){openModal('teamModal');return}selected=PLACES.find(p=>p.id===id);$('#photoTitle').textContent=selected.name;$('#photoDesc').textContent=selected.desc;$('#photoChallenge').textContent='Défi photo : '+selected.challenge;$('#photoInput').value='';$('#preview').style.display='none';openModal('photoModal')}
async function compress(file){const img=await createImageBitmap(file),max=1400,scale=Math.min(1,max/img.width),c=document.createElement('canvas');c.width=Math.round(img.width*scale);c.height=Math.round(img.height*scale);c.getContext('2d').drawImage(img,0,0,c.width,c.height);return new Promise(r=>c.toBlob(r,'image/jpeg',.72))}
async function submitPhoto(){const f=$('#photoInput').files[0];if(!f)return toast('Prenez ou choisissez une photo');const btn=$('#submitPhoto');btn.disabled=true;btn.textContent='Envoi…';try{const blob=await compress(f);let record={id:crypto.randomUUID?.()||String(Date.now()),placeId:selected.id,place:selected.name,time:new Date().toISOString(),status:'pending'};if(CONFIG.API_URL){const data=new FormData();data.append('action','submit');data.append('team',JSON.stringify(team));data.append('place',JSON.stringify(selected));data.append('photo',blob,'preuve.jpg');const r=await fetch(CONFIG.API_URL,{method:'POST',body:data});if(!r.ok)throw new Error('Envoi impossible');const j=await r.json();record.id=j.id||record.id}else{record.preview=await blobToDataURL(blob)}subs=subs.filter(s=>s.placeId!==selected.id);subs.push(record);save('jze2_subs',subs);closeModal('photoModal');render();toast(CONFIG.API_URL?'Photo envoyée':'Preuve enregistrée en démonstration')}catch(e){toast(e.message||'Erreur pendant l’envoi')}finally{btn.disabled=false;btn.textContent='Envoyer la preuve'}}
function blobToDataURL(b){return new Promise(r=>{const x=new FileReader;x.onload=()=>r(x.result);x.readAsDataURL(b)})}
function toggleTracking(){if(watchId){navigator.geolocation.clearWatch(watchId);watchId=null;lastPos=null;render();return}if(!navigator.geolocation)return toast('Géolocalisation indisponible');watchId=navigator.geolocation.watchPosition(pos=>{const p={lat:pos.coords.latitude,lon:pos.coords.longitude,acc:pos.coords.accuracy};if(lastPos&&p.acc<70){const d=hav(lastPos,p);if(d>3&&d<250){distanceM+=d;save('jze2_distance',distanceM)}}lastPos=p;render()},()=>{watchId=null;render();toast('Autorisez la géolocalisation')},{enableHighAccuracy:true,maximumAge:4000,timeout:15000});render();toast('Suivi de distance activé')}
function hav(a,b){const R=6371e3,p1=a.lat*Math.PI/180,p2=b.lat*Math.PI/180,dp=(b.lat-a.lat)*Math.PI/180,dl=(b.lon-a.lon)*Math.PI/180,x=Math.sin(dp/2)**2+Math.cos(p1)*Math.cos(p2)*Math.sin(dl/2)**2;return R*2*Math.atan2(Math.sqrt(x),Math.sqrt(1-x))}
async function refreshRanking(){let rows=[];if(CONFIG.API_URL){try{rows=await fetch(CONFIG.API_URL+'?action=ranking').then(r=>r.json())}catch{toast('Classement indisponible')}}if(!rows.length&&team){rows=[{team:team.name+' (vous)',score:new Set(subs.map(s=>s.placeId)).size}]}if(!rows.length){$('#rankingList').innerHTML='<p>Aucun résultat partagé pour le moment. Le classement collectif apparaîtra après la connexion à Google Sheets.</p>';return}rows.sort((a,b)=>b.score-a.score);$('#rankingList').innerHTML=rows.map((r,i)=>`<div class="rank"><div class="medal">${i<3?['🥇','🥈','🥉'][i]:i+1}</div><div><b>${r.team}</b><small>${r.score} lieu${r.score>1?'x':''}</small></div><strong>${r.score}</strong></div>`).join('')}
function openModal(id){$('#'+id).classList.add('open')}function closeModal(id){$('#'+id).classList.remove('open')}
$$('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));$$('[data-open]').forEach(b=>b.onclick=()=>openModal(b.dataset.open));$$('[data-close]').forEach(b=>b.onclick=()=>closeModal(b.closest('.modal').id));$$('[data-mode]').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;$$('[data-mode]').forEach(x=>x.classList.toggle('selected',x.dataset.mode===mode))});
$('#saveTeam').onclick=async()=>{const name=$('#teamInput').value.trim(),code=$('#codeInput').value.trim().toUpperCase();if(!name||!code)return toast('Nom et code requis');team={name,code,mode};save('jze2_team',team);if(CONFIG.API_URL)fetch(CONFIG.API_URL,{method:'POST',body:JSON.stringify({action:'register',team})}).catch(()=>{});closeModal('teamModal');render();toast('Équipe enregistrée')};
$('#photoInput').onchange=()=>{const f=$('#photoInput').files[0];if(f){$('#preview').src=URL.createObjectURL(f);$('#preview').style.display='block'}};$('#submitPhoto').onclick=submitPhoto;$('#trackBtn').onclick=toggleTracking;$('#returnBtn').onclick=()=>{if(!team)return openModal('teamModal');returned=true;save('jze2_returned',true);if(CONFIG.API_URL)fetch(CONFIG.API_URL,{method:'POST',body:JSON.stringify({action:'return',team,time:new Date().toISOString()})}).catch(()=>{});render();toast('Retour signalé')};$('#refreshRank').onclick=refreshRanking;
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('#installBtn').hidden=false});$('#installBtn').onclick=async()=>{if(deferredPrompt){deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;$('#installBtn').hidden=true}};
if(team){$('#teamInput').value=team.name;$('#codeInput').value=team.code;mode=team.mode}$$('[data-mode]').forEach(x=>x.classList.toggle('selected',x.dataset.mode===mode));renderFilters();render();refreshRanking();tick();setInterval(tick,1000);setInterval(refreshRanking,CONFIG.REFRESH_MS);if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js');
